### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by cycl0ne** [vekexasia/tesla-ts#9]
when using your example:
      const api = new TeslaAPI(username, password);
        api.vehicles().then((vehicles)=> {
            console.log('my vehicles: ', vehicles);
            // get the first vehicle!
            const vehicle = vehicles[0];
          })
          .catch((error) => console.warn(error));

i get:

Error: Request failed with status code 400
    at createError (/home/poweros/tibberts/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/poweros/tibberts/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/poweros/tibberts/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

**Comment by cycl0ne** [comment]
to give more input:
    data: {
      response: null,
      error: 'Endpoint deprecated: Please update your App.',
      error_description: ''

Seems you need to update your code:
https://tesla-api.timdorr.com/api-basics/authentication
